version: '3'

services:
  assemble:
    image: austintraver/monolith:latest
    build:
      context: .
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    privileged: true
    container_name: monolith
    ports:
      - "10122:22"
    working_dir: /root/scratch
    hostname: monolith
    domainname: monolith.local
